#imports
import nextcord
from nextcord.ext import commands
from craiyon import Craiyon
from PIL import Image
from io import BytesIO
import time
import base64

# call bot command in discord server (!)
bot = commands.Bot(command_prefix="!", intents = nextcord.Intents.all())

# check if bot runs in server
@bot.event
async def on_ready():
    print("Bot is Running!")

# generate AI ART
@bot.command()
async def generate(ctx: commands.Context, *, prompt: str):
    # expected time of arrival
    ETA = int(time.time() + 60)
    msg = await ctx.send(f"Grab a drink, this will be ready <t:{ETA}:R>")
    generator = Craiyon()
    result = generator.generate(prompt)
    image = result.images
    # decode image and thank craiyon.com
    for i in image:
        image = BytesIO(base64.decodebytes(i.encode("utf-8")))
        return await msg.edit(content="Generated by **craiyon.com**", file=nextcord.File(image, "generatedImage.png"))

# run Discord bot token from token.txt
with open('token.txt', 'r') as file:
    token = file.readlines()[0]
bot.run(token)